### ISSUE TITLE
Kasjs - HomeWork#7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#101]
1. Функция preparingObj(oldObj){ что делает.
Она должна либо делать первую букву слова большой, либо обрезать описнаие до 15 символов.
2. fillDiv(item) должна быть функцией, которая обрабатывает элемент (при вызове должно быть fillDiv(newData[i])).
3. var adBat = selector('#addB');
    var disableButton = function () {
        adBat.className = 'btn btn-sm btn-danger disabled';
    }
Почему такие разные названия addB и  adBat
4. function removeElement() {
    container.addEventListener('click', function (event) {
        if (event.target.tagName == 'A') { - эта проверка обязательна?

5. Зачем поле Quantity . Что в нем должно быть?
6. Если делать такие шаги:
Зайти и нажать дважды Add selected/Display all, то добавятся 20 элементов, но при этом 
total:10????
Потом нажать Del Selected - значение уже 19??
Что имеется в виду под Selected, если я ничего не нажимала. Стоит сделать тогда значения по умолчанию в инпутах. Либо говорить пользователю, что он делает не так и что он может делать. Вот кнопку + Add new element Вы делаете disable, если больше добавлять нечего - это ОК

**Comment by Kasjs** [comment]
1.Функція preparingObj(oldObj)  - перший пункт не зрозумів а чому ця функція не може робити першу букву великою і обрізати символи до 15.
2. fillDiv - переробив як ви написали тепер він приймає аргумент newData[i].
3. Назви кнопок змінив.
4. function removeElement() {
container.addEventListener('click', function (event) {
if (event.target.tagName == 'A') - перевірка потрібна тому що я вішав event не на link а на весь div container. Тому перевіряю чи була натиснута саме link. Чи тут можна зробити ефективніше?.
5. Інпут Quantity був неробочий тому я його зробив неактивним тепер все працює.
6.Кнопку Add selected/Display all перейменував, тепер вона Add selected і добавляє елементи які введені в інпутах.А коли нічого не введено вона нічого не виводить.

Плюс добавив перевірку яка робить наступну логіку :  після того як вибрані елементи добавилися ми їх видаляємо кнопкою  Del Selected і коли total = 0 то масив переписується і ми знову можемо добавляти нові елементи не обновляючи сторінки :).

**Comment by nromanen** [comment]
Почнемо з кінця. Кнопка - це ОК. Але. Ми маємо видалити всі елементи по одному, і тільки тоді вона стає активною. Можливо, краще зробити ще одну кнопку "Видалити всі елементи"? Можна ще зробити варіант - додавати по колу елементи. Тобто коли закінчиться колекція, то починати додавати з першого елемента. А можна сказати, що будемо додавати, поки кількість елементів, що вдіображаються, не буде більшою за довжину початкового масиву (if(total.innerHTML < data.length-1)). Варіантів може бути декілька. Але можете зупинитися просто на ще одній кнопці - видалити все. 
2. Треба розбіратися з логікою роботи Вашого додатка. Якщо ми додали декілька елементів по одному (наприклад 2), а потім додаємо з 1 по 10 10 елементів, то... count = 10. Чому? Потім додаємо ще один єлемент. Count змінюється на  3. Треба якось визначитися. Я би count робила глобальноью змінною і змінювала її завжди, коли додавала б елементи на сторінку (неважливо, колекцією чи по одному елементу).
3. Що  робить кнопка "Del selected" ? І що вона має видаляти, якщо будуть додаватися елементи і з колекції і по одному? Тому треба або забрати цю кнопку. Або зробити можливість додавати чи тільки вибрані елементи, чи тільки додавати по одному. І тоді ця кнопка буде активною, якщо ми до цього додаємо колекцію.
4. Зробити дві функції:  transformObject(item), яка буде перетвореювати наш об'єкт згідно вимог. Друга  formatObject (data)  - це та, що у Вас є - в циклі викликати transformObject. Тоді при додаванні колекції ми викликаємо всередині  formatObject (data.slice.....), а при додаванні по одному елементу викликаємо transformObject(data[count])

**Comment by Kasjs** [comment]
1.Видалив кнопку Del selected,тепер для колекцій  є одна кнопка Add selected і всі елементи видаляються лінком (remove).
2.count у мене і був глобальним тільки трохи криво рахує :).
3.Видалив кнопку.
4.функцію  transformObject(item) зробив яка запускається в циклі .
