### ISSUE TITLE
KroyaloPetro/lesson - homework#7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#102]
1. На страничке кнопки 'Clear' и 'Delete' стоят рядом. Лучше кнопу 'Clear' поднять выше - к инпутам Start, End, Count. Она же относится к ним. 
2. Если мы не можем добавить элемент после добавления всех 10 по одному, то почему мы можем загрузить коллекцию много раз. Должна быть согласованность. Наверное, только один раз мы должы добавлять коллекцию.
3. Логичнее в id="count" просто выводить общее количество элементов на страничке, а не считывать с него значение, чтобы выводить следующий элемент.

**Comment by fredis0629** [comment]
1) выполнил.
2) я нашол лазейку теперь такого не будет :) .
3) id="count" я использую и для хранения общего количества фоток и для того что б знать какую картинку отображать. зделал я ето бля того что б не вводить еще одной переменной (глобальной).

**Comment by nromanen** [comment]
resultContainer.addEventListener("click",function(event){
	event.preventDefault();
	if (event.target.tagName == "A"){
		event.currentTarget.removeChild(event.target.parentNode.parentNode.parentNode);
		count.innerHTML = (Number(count.textContent)-1);
	}
});
Вас не смущает строка event.currentTarget.removeChild(event.target.parentNode.parentNode.parentNode)???
Соответственно обратите внимание на функцию createNewPictureDiv(item). По-моему, там слишком много lastChild. Если Вы это сделали специально, то объясните, пожалуйста, почему.

**Comment by fredis0629** [comment]
1) Строка :

**Comment by fredis0629** [comment]
1) Строка :

**Comment by fredis0629** [comment]
1) Строка :
event.currentTarget.removeChild(event.target.parentNode.parentNode.parentNode)
вообще не смущает. У меня оброботчик висит "в самом верху" (на диве в котором находятся все елементы), соответственно что бы сообщить ему какой именно див из его дитей удалять мня нужно двигатся от таргета вверх до дива class="col-sm-3 col-xs-6" (контейнер одной картинки). другого способа добратся к ниму в той точки я незнаю. убрать подобную строку можно переместив оброботчик события на див class="col-sm-3 col-xs-6". все что можно изменить в етой строке так это заменить event.currentTarget на resultContainer.

2) уменьшить ихнее количество можно лиш добавлением еще одной переменной, чего я но хотел делать и пытался избежать всеми силами + это неплохая тренеровка что бы запомнить как пишется lastChild :) .
(Это будет выглядеть примерно так же как написал ValentynTymku : 
"var childItem = createElement('div', {'class' : 'info-wrapper'});
	childItem.appendChild(createElement('div', {'class' : 'text-muted'}, obj.id + ": " + obj.name));
	childItem.appendChild(createElement('div', {'class' : 'text-muted'}, obj.description));
	childItem.appendChild(createElement('div', {'class' : 'text-muted'}, obj.date));
	childItem.appendChild(createElement('button', {'class' : 'btn btn-sm', 'onClick' : 'removeElement(this)'}, 'Удалить'));

	var item = createElement('div', {'class' : 'col-sm-3 col-xs-6'});
	item.appendChild(createElement('img', {'src' : obj.url, 'alt' : obj.name, 'class' : 'img-thumbnail'}));
	item.appendChild(childItem);")

**Comment by nromanen** [comment]
А Вам не кажется, что тогда это паранойя - и так четко следить, на что Вы навешиваете eventListener, и проверять if (event.target.tagName == "A")?
![kroyalo_7](https://cloud.githubusercontent.com/assets/4123050/11480950/1231ac70-97a3-11e5-949d-0fb1cc050669.png)

**Comment by fredis0629** [comment]
Если у вас есть предложение как от етого избавится с радостью выслушаю, сам я не вижу более верного, простого способа.

**Comment by fredis0629** [comment]
Если у вас есть предложение как от етого избавится с радостью выслушаю, сам я не вижу более верного, простого способа. А проверка там нужна что б не было удаления при нажатии на картинку вместо delete.
Как у вас получилось создать такой скрин?

**Comment by fredis0629** [comment]
Если у вас есть предложение как от етого избавится с радостью выслушаю, сам я не вижу более верного, простого способа. А проверка там нужна что б не было удаления при нажатии на картинку вместо delete.
Как у вас получилось создать такой скрин?
понятия не имею как это могло выскочить, но принял к свединию и зделал так что теперь етого непроизойдет.

**Comment by nromanen** [comment]
1. appendChild всегда добавляет элемент к последнему узлу, поэтому я не вижу необходимости писать такого типа строки:
itemTemp.lastChild.appendChild(createNewElement("div",{class : classes.txt}, cutDescription(item.description)));

При вашей реализации можно спокойно убрать if (event.target.tagName == "A"). Вы же потом четко указываете на что будете цеплять обработчик (itemTemp.lastChild.lastChild.appendChild(createNewElement("a",{ href : "#"},"delete"));)

2. Я предлагаю написать так:
а) (если без    if (event.target.tagName == "A"))
function createNewPictureDiv(item){
	var itemTemp = createNewElement("div",{class: classes.col});
	itemTemp.appendChild(createNewElement("img",{
		class : classes.image,
		src	  : item.url,
		alt	  : correctName(item.name)
	}));
	itemTemp.appendChild(createNewElement("div", {class : classes.info}));
	itemTemp.appendChild(createNewElement("div",{class : classes.txt}, (item.id+": "+correctName(item.name)))); 
	itemTemp.appendChild(createNewElement("div",{class : classes.txt}, cutDescription(item.description)));
	itemTemp.appendChild(createNewElement("div",{class : classes.txt}, formateDate(new Date(item.date))));
	itemTemp.appendChild(createNewElement("div",{class : classes.txt}));
	itemTemp.lastChild.appendChild(createNewElement("a",{ href : "#"},"delete"));
	return itemTemp;
}

И тогда действие на delete описать проще 
event.currentTarget.removeChild(event.target.parentNode.parentNode); 

б) (с использованием    if (event.target.tagName == "A"))
function createNewPictureDiv(item){
	...
	itemTemp.appendChild(createNewElement("a",{ href : "#"},"delete"));
	return itemTemp;
}
и тогда 
resultContainer.addEventListener("click",function(event){
	event.preventDefault();
	if (event.target.tagName == "A"){
		event.currentTarget.removeChild(event.target.parentNode);
		count.innerHTML = (Number(count.textContent)-1);
	}
});
Но это мое мнение, а решать Вам. Понятно, что свой код всегда понятнее, логичнее и безбажнее ;)
