### ISSUE TITLE
OlegOdoviichuk - homework #8

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#107]
1. Трижды повторяется код, который относится к функциям 
showErrorMsg, hideErrorMsg, showSuccessMsg, hideSuccessMsg, showForm, hideForm
Надо от этого избавиться. Вспомните как мы можем в js обращаться к свойствам в объекте (DOMElements["errorMsg"] например)

**Comment by eRR0R4ik** [comment]
FIXED
