### ISSUE TITLE
MolodiyVolodymyr - work3

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#20]
Поместить третье задание в отдельную папку!
Форматирование кода надо обязательно поправить

```javascript
document.getElementById("result").innerHTML += "Первая кость:" + SPACE + first + SPACE + "Вторая кость:"+ SPACE + second + "<br>";
```
Эта строка должна на экране выводиться первой. Надо ее переместить выше.
```javascript
else if (first==second ){
    document.getElementById("result").innerHTML += "Выпал дубль. Число" + SPACE + first+ "<br>"
}
```
Эта информация должна высвечиваться всегда когда дубль. ДАЖЕ если "Две единицы" или "две шестерки"
Сейчас же эта строка напечатается только если НЕ две единицы или две шестерки.
Надо поправить.

**Comment by volodymyr9122** [comment]
Corrected

**Comment by dreemius** [comment]
Зачем там document.write?
Или обоснуй пожалуйста или замени его на innerHTML
