### ISSUE TITLE
zhartole work  4

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#29]
1. Переделать viewDouble для того, чтобы не проверять трижды first_dice == second_dice 
2. Название функции viewResult не соответствует тому, что она делает.
3. Сделать одну функцию которая будет печатать строки. Ей надо будет передавать текст как параметр.

**Comment by zhartole** [comment]
Fixed.
 Lesson 2 && Lesson 3 too

**Comment by nromanen** [comment]
Переделать viewDouble для того, чтобы не проверять трижды first_dice == second_dice

**Comment by zhartole** [comment]
В функції viewDouble двічі перевіряється  first_dice == second_dice.
1 раз для того щоб визначити чи значення = 1 || 6. 
2 раз щоб визначити чи значення це дубль
Можна видозмінити першу перевірку і записати її  ( first_dice == 1 && second_dice == 1 || first_dice == 6 && second_dice == 6 ) ?
Проте код стає довшим.

Я вірно зрозумів Ваше зауваження? Якщо хід моєї думки невірний, тоді направте, будь ласка, у вірне русло :)
 [Посилання в репозиторій] (https://github.com/dreemius/JavaScriptFundamentals2/blob/master/zhartole/HW_Lesson_4/play_dice.js)

**Comment by nromanen** [comment]
function viewDouble(first_dice, second_dice){
	if (first_dice == second_dice){
		return (first_dice == 1) ? ('<div class="double">Two 1' + '<br></div>'): (first_dice == 6) ?'<div class="double">Two 6' + '<br></div>': '<div class="double">Double ' + first_dice + '<br></div>'; 
	}
	 return "First Dice  " + first_dice + "Second Dice " + second_dice + "<br>";
}
