### ISSUE TITLE
AndrewJasinsky - work2

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#37]
```javascript
<script type="text/javascript" async>
```
А разве можно использовать async в случае встроенных скриптов?

Task_4/Task_4.js
Имелось ввиду поочередно одной и той же переменной поочередно назначать разные значения.
А у тебя микс. То преобразование то назначение.

Task_5/Task_5.js
Надо было три раза сделать инкримент для переменной.
var i =1;
i++;
i++;
i++
Поправь пож.

Task_6/Task_6.js
Надо было назначить переменной какое то значение и потом ее преобразовывать.

**Comment by yakutcv** [comment]
Женя, что собственно исправить?

**Comment by dreemius** [comment]
Сори, уже коммент видно

**Comment by yakutcv** [comment]
Done.

**Comment by dreemius** [comment]
Касательно шестого
Имелось виду как то так:

```javascript
var a = "10";
console.log(a);
a = Number(a); console.log(a);
a= String(a);  console.log(a);
a= parseInt(a+"test");console.log(a);
a= Boolean(a);console.log(a);
```
апдейтни и закроем.

**Comment by yakutcv** [comment]
Done.
