### ISSUE TITLE
Anatole - work3

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#39]
if((first && second) == 1)

Такое условие не сработает.
(first && second) означет что *существует* и та и другая переменная, а не то что оно будут равны.

var first  = 1;
var second = 3;
(first && second) -> true (обе существуют)
потом true в сравнеия интерпретируется в 1 (true -> 1)
 if( 1== 1)
И как результат это условие будет всегда выполнятся.

Надо переделать.

**Comment by Kasjs** [comment]
??  условие работает и выполняеться только когда нужно
