### ISSUE TITLE
AlexHristodul - work2

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#40]
var a = parseInt("2107alex");
console.log (a);
var a = !!"2107alex";
console.log (a);
var b = 28;
alert (a+b);

Надо было взять одну переменную, назначить ей какое то значение и потом преобразовывать поочередно эту переменную, а не переназначать ее.
var a = "2107alex";
a= parseInt(a);

**Comment by Hristodul** [comment]
All done :)
