### ISSUE TITLE
AlexHristodul - Homework# 5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#41]
var filterEvenObj = function(a){
 
	return ((someObj!==1 && someObj!==2 ) || 
			(someObj==1 && a%2!==0) || 
			(someObj==2 && a%2==0)) 
			|| false;

}; - что должна делать функция? 

2. var filterCount = function (id) {
	return id <=maxHandllerObj;
}; - надо ли писать целую функцию для проверки, что число меньше заданого???

3. Функция filterByConfig не выполняет то, что она должна делать, потому что filterEvenObj
всегда возвращает true.

4. var newDescr  - надо было урезать текст до 15 символов. У Вас - до 14.

Замечания :
5.   var id = data[key].id; - зачем, если можно дальше просто написать

        if(filterEvenObj(data[key].id) && filterCount(data[key].id) ). 
  Но если так легче понимать, то можно оставить.

6. Какова смысловая нагрузка для переменной someObj?
7. Если есть метод init (который по названию делает инициализацию, то не логичнее
ли в нем задать переменную maxHandllerObj?

**Comment by Hristodul** [comment]
Complete !!!
