### ISSUE TITLE
zhartole - Homework# 5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#43]
1. задайте переменную в которой укажите сколько элементов будете обрабатывать. В какой переменной хранится это количество?

2. Для поля Name: с помощью функций работы со стрингами ДЕЛАЕТЕ первую букву большой, остальные маленькие - данная функциональность не реализована (из дАНИЯ -> Дания).

3. Желательно каждое преобразование делать в отдельной функции, а то логика размазана по всему коду.

4. Преобразование в определенный формат даты - точно должна быть отдельная функция типа Convert...

**Comment by zhartole** [comment]
1. Это количество (точнее варианты сортировки) хранятся в переменной NUMBERS_TO_DISPLAY, так же ниже закоментировано альтернативное решение;
2. эта функциональность реализована в переменной capitalizedFirstLetter;
Остальное исправлю.
Спасибо.

**Comment by zhartole** [comment]
Fixed.
And i also fixed Lesson 2 && Lesson 4 too.  
Can you check it ?

**Comment by nromanen** [comment]
В какой переменной хранится количество обрабатываемых элементов?

**Comment by zhartole** [comment]
>> В какой переменной хранится количество обрабатываемых элементов?

 NUMBER_OF_IMAGES ; link:  [folder in repository] (
https://github.com/dreemius/JavaScriptFundamentals2/blob/master/zhartole/HW_Lesson_5/debug/gallery.js)


**I also fixed [Lesson 2] (https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_2)** && **[Lesson 4] (https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_4)** and done **HW of [lesson 6] (https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_6)**
Can you check it ?

I have a little **question**.
How is better:
Put 
```javascript
elementsName.appendChild(groupName)
```
when we create element of div or during creation all div elements?

**Thnx.**
