### ISSUE TITLE
KroyaloPetro - homework # 5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#44]
1. Не совсем правильно говорить, что MAX - это отдельная переменная. А если MAX будет больше колиечства наших объектов? Пожтому лучше проверку if ((index < MAX) делать с длинной data.
2. Название переменных и функций лучше делать адекватными : correctName, cutDescription(description), переменные namec и datef - что значат?

**Comment by dreemius** [comment]
(index < MAX)&&(index >= STARTP-1)&&(index < ENDP)
Вынести проверку в функцию типа isAvailableRange()

Первый вызов занести в функцию.

**Comment by fredis0629** [comment]
все в корень переделал.

**Comment by nromanen** [comment]
1. Если START_P позиция начала, а END_P - позиция последнего itemа, то непонятно, почему для вывода всех значений я должна указывать START_P = 0, END_P=10 (надо либо с 0 по 9, либо с 1 по 10)
2. Совсем непонятна реализация вывода по 4 в ряд. Сама "четверка" скрыта где-то в литеральном значении. 
function isPrint(buffForDivRow, index, START_P, END_P){
	return ((buffForDivRow == 3)||((index+1) == (END_P-START_P)));
} - для чего нужна эта функция???
Подсказка: if (buffForDivRow == 3)

**Comment by fredis0629** [comment]
2)
?
что за  function isPrint(buffForDivRow, index, START_P, END_P){ return ((buffForDivRow == 3)||((index+1) == (END_P-START_P))); }  Де вы это взяли?
там нет (buffForDivRow == 3) там (buffForDivRow == 4).
 Нужна для проверки вывода, я закидую в HTML по 4 картинки за раз. тоесть сформировал 4 шт. завернул в <div class="row"> и загрузил. + проверка на случай если количество последних загруженых картинок меньше 4 всеровно выводить в HTML, ибо больше не будет.

1)
 я прописывал изначально вариант 1-10. но потом вышло так что более удобно 0-10 (меньше поправочных 1 нужно вносить в код (всего одну вставил)). тоесть зделал так чисто из личного удобства.
Исправить на: (1-10), (0-9) или не исправлять?

**Comment by fredis0629** [comment]
про литеральноезначение ни слова не понял.
"Сама "четверка" скрыта где-то в литеральном значении"- это вопрос?
еслида то я вроде уже ответил

**Comment by nromanen** [comment]
Если мы хотим выводить  по n в ряд, то надо ввести ITEM_PER_ROW = 4 (допустим). И тогда
if (MAX_DISPLAY < (END_P-START_P)) { END_P = START_P + MAX_DISPLAY };
	data.slice(START_P,END_P).forEach(function (item, index){
		resultHTML += replaceItemTemplate(itemTemplate, item);
		buffForDivRow++;
		if (buffForDivRow == ITEM_PER_ROW){
			buffForDivRow 	= 0;
			printInHTML('<div class="row">'+resultHTML+'</div>');
			resultHTML	  	= "";
		}
	});
	printInHTML('<div class="row">'+resultHTML+'</div>');
