### ISSUE TITLE
AndreyTymshuk - homework#4

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#47]
1. Функция getRndElement(one, two), судя по названию, дожна возвращать случайный элемент. Она разве это делает?
2. Написать функцию, которая будет печатать строки. Параметр - строка, которая печатается, а не отдельно функции  getRndElement, youWin, ...
3. Если оба числа равны 1, то вывести  "Две единицы"; если оба числа равны 6, то вывести 
"Две шестерки".

**Comment by tymabgd** [comment]
Спасибо что указали на ошибки. Исправил.

**Comment by nromanen** [comment]
1 строка       if (first == second) {
        getIndex("Выпал дубль. Число: " + first);
    }

                   //Проверка на 1
2 строка     if (first == second && first == 1) {
        getIndex(" Две единицы");
    }

    //Проверка на 6
3. строка    if (first == second && first == 6) {
        getIndex(" Две шестерки");
    }

В 1 строке Вы проверяете, что first == second. В 2 строке и 3 строке Вы дублируете эту проверку. Мы не  должны еще раз проверять это условие, а просто при равенстве first и second, делать потом дополнительную проверку, что эти числа могут быть 1 или 6

**Comment by tymabgd** [comment]
Исправил.
