### ISSUE TITLE
BogdanAkrybai homeWork#5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#54]
1. Преобразование даты лучше вынести в отдельную функцию. Легче будет и ориентироваться в Вашем коде и, возможно, что-то изменить.
2. Задание было 
В оригинальном массиве 15 элементов. В вашей переменной должно быть число которое показывает сколько элементов будет в новом массиве. 
А Вы делаете лишние преобразования (дата, имя, etc) для всех элементов массива, а потом все элементы фильтруете (по индексу, фактически). И не создаете новый массив, а просто переделываете DOM.
Лучше сдлеать функцию, которая будет возвращать новый массив.

**Comment by pro360ua** [comment]
1. fixed 
2. это условие было к simple заданию, а в этом задании нужно было сделать немножко по-другому
