### ISSUE TITLE
VildanovVladislav - homework #5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#57]
Надо было обработать массив data. Не менять index.html.
Начните хотя бы с того, что напишите функции, которые будут делать преобразования отдельных полей объектов, заданных в data.js - даты, названия, описания.

**Comment by divinez122** [comment]
Переделал в gallery.js

**Comment by nromanen** [comment]
В следующий раз перед коммитом проверяйте как работает Ваш код
