### ISSUE TITLE
Kasjs - homework#5

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#59]
1. Если есть больше одной строки кода для преобразования какой-то сущности (например, name), то лучше это делать в одной функции, а потом просто ее один раз вызвать. Так код бугче читается. 
                data[i].name = data[i].name.toLowerCase();
		data[i].name = data[i].name.replace(/[^abc]/,data[i].name.charAt(0).toUpperCase());
С date аналогично. 
3. На страничке Вы сделали выбор значений (количество, с, по). Эта функциональность работает? Если да, то каким образом?

**Comment by Kasjs** [comment]
Инпути я поставил но в коде не организовал.

**Comment by Kasjs** [comment]
пофиксил

**Comment by nromanen** [comment]
ОМГ.
Так вот откуда все началось. Думаю, сегодня всем Женя объяснил, что нечасто (мягко говоря) возвращается из функции значение, которое передаются как аргумент.
Пожалуйста, избавьтесь от передачи index вторым аргументом почти во всех функциях.

**Comment by Kasjs** [comment]
fixed

**Comment by nromanen** [comment]
Дійсно, код став набагато красивіший and readable
