### ISSUE TITLE
zhartole - work2

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#61]
Task_5/Task_5.js
Имелось в виду 
i++
i++
i++
У тебя то же 3 но не так как надо было.

Task_6/Task_6.js
Взять одну переменную и поочередно преобразовать ее в каждый из типов.

Во первых надо было назначить переменной какое то изначальное значение. А тотот что то типа.
```
var a ="10";
console.log(a);
a = Number(a); // переназначение
console.log(а); 
```

**Comment by zhartole** [comment]
Done - [link](https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_2)
