### ISSUE TITLE
ValentynTymku - homework # 6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#62]
return ( i >= param.firstItemIndex && i <= param.lastItemIndex && i <= maxItemIndex) ? true : false;
Никаких сомнений по поводу этой 37 строки?

**Comment by hashcv** [comment]
return ( i >= param.firstItemIndex && i <= param.lastItemIndex && i <= maxItemIndex)

??

**Comment by nromanen** [comment]
Точно
