### ISSUE TITLE
AlexHristodul - Homework #6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#64]
Код типа
var lastDiv1 = document.createElement('div');
	lastDiv1.className = "text-muted";
	lastDiv1.innerHTML = data[0].id + ' ' + newName(data[0].name);
	thirdDiv.appendChild(lastDiv1);
встречается несколько раз.
Такое ощущение, что напрашивается функция

**Comment by Hristodul** [comment]
All complete !!!

**Comment by Hristodul** [comment]
Кстате почему у меня Homework №4 в Exele не закрыто ???

**Comment by nromanen** [comment]
Не закрыто, наверное, потому, что фон все равно давит на текст. Но сам рисунок очень классно. Закрываю Вам за это таск ;)

**Comment by Hristodul** [comment]
Спасибо :)
