### ISSUE TITLE
Zhartole - Work3

### ISSUE THREAD

**Issue by dreemius** [dreemius/JavaScriptFundamentals2#7]
Переименуй папку или как логин в github или как твое имя

Наименование переменных в одном стиле!
```javascript
var first;
var second;
```
не должны быть глобальными, в каждой функции свои

```javascript
var shots_Player_1; //shots = 15;
    for (shots_Player_1 = 0; shots_Player_1 < 15; shots_Player_1++) {
```
более правильно и короче
```javascript
    for (var shots_Player_1 = 0; shots_Player_1 < 15; shots_Player_1++) {
```

Вынеси в переменную 
document.getElementById("Result-details_Player-1")

total_Player_1 как раз должна быть глобальной. Тогда из любой функции можно будет к ней получить доступ.

```javascript
var drop_down;
function hidetxt(type) {
    param=document.getElementById(type);
    if(param.style.display == "none") {
        if(drop_down) drop_down.style.display = "none";
        param.style.display = "block";
        drop_down = param;
    }
}
```
попробуй упростить, слишком сложно.

**Comment by zhartole** [comment]
fixed
