### ISSUE TITLE
Kasjs - homework #6 

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#72]
1. Переделать функцию filterObject, не меняя длины массива.
2.Написать функцию преобразвания даты и тогда ее применять в функции formatObject.
3. Зачем функцию create(element) делать внутренней?

**Comment by Kasjs** [comment]
fixed

**Comment by nromanen** [comment]
1. Зачем почти во всех функциях передавать index и возвращать весь массив data?

**Comment by Kasjs** [comment]
индекс передавал потому что в в функции formatObject () ети две функции должны перенимать аргумент итератора и форматировать все объекты массива.А возвращал уже новый  изменённый массив из функций.
function formatObject () {
	for (var i = 0; i < newData.length; i++) {
		preparingObj(newData,i);
		formatDate(newData,i);
	}

**Comment by Kasjs** [comment]
незачем затупил, исправил :)

**Comment by nromanen** [comment]
:)
function formatDate(oldDate){
	var formDate = new Date(oldDate);
	...
	return year + "/" + month + "/" + day + " " + (hour < 10 ? "0" + hour : hour) + ":" + (minutes < 10 ? "0" + minutes : minutes);
}

function formatObject () {
	for (var i = 0; i < newData.length; i++) {
		...
		newData[i].date = formatDate(newData[i].date);
	}
		...
}


Попробуйте по такому образцу исправить preparingObj

**Comment by Kasjs** [comment]
ці три функції змінив у всіх уроках в яких вони були організовані.Стало краще виглядати дякую :)

**Comment by nromanen** [comment]
:)
