### ISSUE TITLE
zhartole homework#6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#78]
1. В функции inBetween сделать рефакторинг. slice.slice
2. Если Вы объявили глобальную переменную NewGallery, то зачем потом дважды вызывать функцию inBetween?
3. Не очень хорошая идея передавать в doTemplate отдельно  аргументов. Лучше описать эту функцию как такую, которая будет обрабатывать itemData (один item из массива data).

**Comment by zhartole** [comment]
Thnx for remark. 
I check it. ([link to repository](https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_6/debug))
And i also check **HW_7** ([link to repository](https://github.com/dreemius/JavaScriptFundamentals2/tree/master/zhartole/HW_Lesson_7))

**Comment by nromanen** [comment]
function inBetween(START, FINISH) {
	return data.slice(START - 1, FINISH).slice(0,NUMBER_OF_IMAGES);
}
...
newGallery = inBetween(FIRST, LAST).forEach(showImage);
countShow.html(newGallery.length);
Вот это я имела в виду

**Comment by nromanen** [comment]
1. Почему всегда 
Общее колличество:0???
2. Сделайте "Remove" кнопкой. Ссылка - это переход. А у Вас и не ссылка, и не кнопка.

**Comment by zhartole** [comment]
1. Формування загальної кількісті підкореговано;
2. В 6 завданні немає опції видалити елемент. Cкоріш за все, Ви сплутали 6 з 7 завданням.
    Якщо ви маєте на увазі додати цю опцію в 6 завдання, то вкажіть і я це виконаю.

[посилання в репозиторій](https://github.com/dreemius/JavaScriptFundamentals2/blob/master/zhartole/HW_Lesson_6/debug/js/gallery.js)

**Comment by nromanen** [comment]
2. Ну да. Напевно :).

var newData = inBetween(FIRST, LAST);
newData.forEach(showImage);
countShow.html(newData.length);
