### ISSUE TITLE
VildanovVladislav - homework#6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#79]
1. newElement.className=nameClass; Плохая идея переменные называть по-разному. Сначала className, потом nameClass. Тяжело такой код поддерживать. Лучше одинаково называть в данном случае.
2. Если Вы в константу выносите количество элементов elements, то почему не вынести в константу количество картинок в строке?

**Comment by divinez122** [comment]
Так я же в переменную countImages сетаю значение 4 чтоб было 4 картинки в строке

**Comment by nromanen** [comment]
Я имела в виду создать переменную ITEM_PER_ROW=4. А потом уже сравнивать countImages с этим значением, а не с 4.
Переменные принято писать с маленькой буквы 
function createDiv(СlassName, inDiv){
Должно быть function createDiv(сlassName, inDiv){
