### ISSUE TITLE
RomanSabadash - homework# 6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#81]
1. var FIRST_ITEM = 2;
var LASRT_ITEM = 6;
Надо определиться, либо мі считаем "по-компьютерному" - с нуля до length-1, либо "по-человечески" - с единицы до length.
2. У Вас есть переменная newItem = {}; Зачем тогда в newElement передавать отдельно пять аргументов?

**Comment by rsabadash** [comment]
Логичные вопросы)) Пофиксил.
