### ISSUE TITLE
KroyaloPetro - Homework#4

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#82]
1. Math.ceil((Math.random() * x)) - я говорила об этом, что достаточно передавать только основу ч = 6

**Comment by fredis0629** [comment]
Тот рандом прописан был в задании как пример. Я не знаю как пашет Math.ceil поетому если можно то пока не буду ее использовать.

**Comment by nromanen** [comment]
Та конечно, можно. Только я хотела, чтобы Вы посмотрели и исследовали, что и как ;)
