### ISSUE TITLE
OlegOdoviichuk - homework # 6

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#84]
1. var ELEMENTS_START = 5 - лучше назвать START_INDEX.
2. Функцию createEl переделать, чтобы она аргументом получата один item из массива newArr.
3. Создать функцию типа printResult(newArr), которая бы уже для всех елементов массива newArr вызывала createEl.

**Comment by eRR0R4ik** [comment]
Done!
