### ISSUE TITLE
KroyaloPetro - homework#6 

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#87]
1. Неудачно создавать массив из className - classes  = ["row", "col-sm-3 col-xs-6", "img-thumbnail", "info-wrapper", "text-muted"]. Потом легко можно запутаться под каким индексом какой класс находится. Лучше тогда создать объект classes и обращаться по сокращенному имени класса (типа classes.row либо classes["row"]).
2. В функцию createNewInfoDiv(classes, item) не надо передавать classes. В данном случае ее лучше объявить глобальной. Все равно в createNewInfoDiv Вы явно завязываетесь только на конкретных классах. Был бы смысл передавать этот аргумент, если бы вы проходили по всем элементам этого массива, не конкретизируя (for..in).
3. Функция doMod что делает? Возвращает остаток от деления первого числа на второе? Пусть она просто это и делает, т.е. не надо внутри функции писать ++number, лучше увеличивать значение index при вызове doMod.

**Comment by fredis0629** [comment]
1) classes[] изменил на объект.
2) classes зделал глобальной.
3) doMod убрал она всеровно там не нужна. когда делал 7 придумал другой способ как делать проверку.
