### ISSUE TITLE
OlegOdoviichuk - homework #7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#89]
1. в totalCount () надо передавать аргумент.
2. Каждый раз при клике на "Add new element" у Вас вызывается функция changeOptions. Она должна либо каждый раз только обрабатывать один элемент из newArr, либо только один раз отработать, чтобы сформировать измененный (согласно начальным условиям) массив данных.
3. del.addEventListener("click", delArea);   // почему с "keyup" тоже работает?
Мне тоже интересно, почему у Вас работает. Обычно, да и у меня - нет ;)
4. А что будет, если мы уже добавили все элементы нашей коллекции?
Возможно, стоит при исчерпании коллекции сделать кнопку "Add" disable (Если Вам уже об этом рассказывал Женя). В крайнем случае, хотя бы не ничего не делать и выводить Alert("Нечего добавлять").

**Comment by eRR0R4ik** [comment]
Done!

**Comment by nromanen** [comment]
1. Теперь Вы каждому елементу присваиваете название, дату и описание нулевого элемента. Посмотрите, что у Вас выводится при добавлении элемента.
В функции changeOptions(arrObj) Вы должны менять arrObj (только один элемент, там не нужен цикл).
2. Если написать del.addEventListener("keyup", delArea); 
3. console.log() ВСЕГДА перед окончательным коммитом удаляйте.  ;) 
то при нажатии на кропку "Стереть" в браузере очищаются оба поля? У меня FireFox 42.0 ничего не делает, только потом при нажатии любой клавиши клавиатуры удаляется информация.

**Comment by eRR0R4ik** [comment]
RE_FIXED :+1:
