### ISSUE TITLE
RomanSabadash - homework #7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#92]
1. Зачем делать одни и те же ошибки? 
Вы ввели переменную newItem, вот ее и используйте в функции newElement.
2. Зачем такая сложная конструкция:
  getText.value = " ";
  setText.value = getText.value;?
3. Переменная qty - как-то слишком коротко названа. Это аббревиатура от каких слов?
4. Хорошо, что анализируете в функции run, что в коллекции больше нет элементов. Но желательно для удобства выводить сообщение, что добавлять больше нечего (элементов в коллекции нет).

**Comment by rsabadash** [comment]
Я сперва пушнул 7 задание, а потом исправлял по Вашему замечанию 6-е, по этому так получилось с функцией newElement.
qty - сокращенно от quantity (количество), да, как-то не логично получилось)
