### ISSUE TITLE
zhartole - Homework #7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#93]
1. Почему в addAllImg Вы завязались на числе 10. А если в data будет больше или меньше єлементов?
2. Вы в doTemplate передаете то item, то index, то еще что-то (по названиям), какой-то божественный метод получается. Либо уж тогда говорите, что вы всегда в эту функцию передаете индекс элемента (названиями), либо (может, есть смысл) передавайте туда элемент  массива, а не просто индекс.
3. "Remove" должна быть кнопкой, а не ссылкой, зачем переопределять  поведение ссылки? 
      
 С вопросом 
// WHY if if i using ternar operator its dont work correctly (show only first img)?
		// count < 10 ? doTemplate(count) && count++ : disableButton();
разобрались?
Классически тернарный оператор используется для присваивания значения чему-либо, а не для выполнения определенных действий. Оператор && используется для проверки boolean-значений,  а не для того, чтобы что-то выполнять. Мы можем его использовать в js для проверки, что что-то существует (левая часть до &&), а потом присваивания. Вы что  здесь хотите проверять : doTemplate(count)?
4. delImg.addEventListener("click", deleteElement); - нет смысла писать функцию deleteElement, он абольше нигде не будет использоваться (тем более, она внутренняя), поэтому здесь надо использовать анонимную функцию.

**Comment by zhartole** [comment]
Дякую за коментарі!
Виправлено.
[посилання в репозиторій] (https://github.com/dreemius/JavaScriptFundamentals2/blob/master/zhartole/HW_Lesson_7/js/gallery.js)

**Comment by nromanen** [comment]
Мені здається, що після того як ми зробили 'Remove' ми мали б могти додавати ще картинки. А ми не маємо :( 
![zhartole_7](https://cloud.githubusercontent.com/assets/4123050/11502582/5ec921f2-9844-11e5-88a0-a854b57cb0b3.png)

**Comment by zhartole** [comment]
Виправлено!
[посилання в репозиторій] (https://github.com/dreemius/JavaScriptFundamentals2/blob/master/zhartole/HW_Lesson_7/js/gallery.js)
Перевірте, будь-ласка, 6  [issue 6 завдання](https://github.com/dreemius/JavaScriptFundamentals2/issues/78) та 4 завдання  [issue 4завдання](https://github.com/dreemius/JavaScriptFundamentals2/issues/29)

**Comment by nromanen** [comment]
Я перевірила 6 завдання. Написала в кінці зауваження. Можете подивитися.
