### ISSUE TITLE
ValentynTymku - homework #7

### ISSUE THREAD

**Issue by nromanen** [dreemius/JavaScriptFundamentals2#95]
1. Относительно первого задания - мы не ищем легких путей ;) 
2. Переменная count всегда относится к spanу з id = "count". Зачем ее переопределять дважды:
в decItemsCount и в incItemsCount,

**Comment by hashcv** [comment]
fixed :+1:

**Comment by nromanen** [comment]
А комменты в первом задании оставили для эффекта - "Почувствуйте разницу" ;)

**Comment by hashcv** [comment]
для потомков ☺

2015-11-19 9:40 GMT+02:00 nromanen <notifications@github.com>:
